### ISSUE TITLE
Frequency show none

### ISSUE THREAD

**Issue by ken340** [NebraLtd/helium-pycom#1]
My device should run on 915Mhz with the region AS923_1. I realised the Balena file is based on 868, will it work correctly?

**Comment by shawaj** [comment]
The frequency should show none (unless it is a Nebra device).

The region plan should show AS923_1

If that shows correctly then it'll work just fine :-)

**Comment by shawaj** [comment]
@ken340 ^^

**Comment by ken340** [comment]
Thanks for letting me know.

**Comment by shawaj** [comment]
My pleasure @ken340 

If the software has been helpful for you please consider leaving a donation at https://github.com/sponsors/NebraLtd

This will help us to keep developing the open source software and providing updates.
