### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by DonCartega** [NebraLtd/helium-pycom#2]
After many reflashes attempts of different releases when I tried to connect the hotspot to WIFI through the maker app like Pycom App, Nebra App, and also the old Helium App every time when it tries to connect it shows after a while in the app Device disconnected.

**Comment by shawaj** [comment]
@DonCartega do you have any screenshots of the error? Or the exact error message?

**Comment by DonCartega** [comment]
Now is working. I belive it was a firmware issue. I have the latest release installed and is working.
