### ISSUE TITLE
How to change SSID and WPA2-PSK passcode

### ISSUE THREAD

**Issue by ken340** [NebraLtd/helium-pycom#3]
Please advise how to change SSID and passcode after flashing the SDCARD.

**Comment by shawaj** [comment]
@ken340 you can use the Nebra app

**Comment by shawaj** [comment]
@ken340 did you get this working?

**Comment by ken340** [comment]
Hi Aeron,

The pico device does not have a button to activate BT and during startup I am having trouble connecting to the device using BT and the Nebra APP.

However, using the pervious firmware, I saw it is self updating so I left it as it is.

If you need I could help to check connecting it again as the device is now on the latest firmware.

Thank you
Kenneth

**Comment by shawaj** [comment]
@ken340 are you trying to connect to the hotspot within 5 minutes of booting it up?

As it will only advertise Bluetooth for first 5 minutes

**Comment by shawaj** [comment]
Closing as no reply
