### ISSUE TITLE
How to onboard?

### ISSUE THREAD

**Issue by mlowijs** [NebraLtd/helium-pycom#5]
I have flashed a Pycom hotspot with the latest Nebra firmware and am able to get it connected to WiFi. However, when trying to onboard the hotspot using the Pycom app, the Helium Wallet does not show me the Hotspot name and I am not able to press Confirm.

Can you tell me how to get around this?

![77849AB1-0AF1-4A78-A29A-1A57E560A5F8](https://github.com/NebraLtd/helium-pycom/assets/2751421/1e4096fe-97da-4e91-87de-5385b0664094)

**Comment by catsado89** [comment]
Hey there sorry to write in your topic but how were you able to connect it to wifi, via nebra app or pycom app? Does your pycom have the lan port addon?

**Comment by mlowijs** [comment]
Pycom app allowed me to connect to the hotspot and select a network.Sent from my iPhoneOn 19 May 2023, at 18:34, catsado89 ***@***.***> wrote:﻿
Hey there sorry to write in your topic but how were you able to connect it to wifi, via nebra app or pycom app? Does your pycom have the lan port addon?

**Comment by shawaj** [comment]
@mlowijs you need to use the Nebra app.

Also, if you haven't onboarded it to the Helium Network yet you will not be able to unless you send a ticket to https://support.nebra.com and there is a cost of $75 ($50 for the onboarding fee and $25 for our time to do the work)

Will close this as we can only deal with this via the support ticketing system

**Comment by shawaj** [comment]
@mlowijs if you create a ticket, you can add a link to this thread also. And then post back here with the ticket number as well.

Cc @WayneNebra
